### ISSUE TITLE
R code Error when calculate Massey Ratings

### ISSUE THREAD

**Issue by zawmoetun** [martineastwood/penalty#1]
Dear Sir,
I get below euro when I running massey.R. Error is below and see attached data. I have changed column name is data but error is happen.
[E0.csv.txt](https://github.com/martineastwood/penalty/files/72721/E0.csv.txt)

Error in solve.default(X, y) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0

Code is here

f<- file.choose('E0.csv')
df<-read.csv(f)
num_teams <- length(unique(c(df$team1, df$team2)))
num_games <- nrow(df)
teams <- unique(c(df$team1, df$team2))

X <- matrix(0, nrow=num_teams, ncol=num_teams)
for(i in 1:nrow(df)){
  h <- match(df$team1[i], teams)
  a <- match(df$team2[i], teams)
  X[h, a] <- X[h, a] - 1
  X[a, h] <- X[a, h] - 1
}

for(i in 1:nrow(X)){
  X[i, i] <- abs(sum(X[i, ]))
}
X[nrow(X), ] <- 1

y <- sapply(teams, function(x, df){
  home <- subset(df, team1 == x)
  away <- subset(df, team2 == x)
  goals_for <- sum(home$team1_goals) + sum(away$team2_goals)
  goals_away <- sum(home$team2_goals) + sum(away$team1_goals)
  goals_for - goals_away
}, df=df)
y[length(y)] <- 0

goals_for <- sapply(teams, function(x, df){
  home <- subset(df, team1 == x)
  away <- subset(df, team2 == x)
  home_goals <- sum(home$team1_goals)
  away_goals <- sum(away$team2_goals)
  home_goals + away_goals
}, df=df)

ratings <- solve(X, y)
names(ratings) <- teams

g <- matrix(0, nrow=num_teams, ncol=num_teams)
for(i in 1:nrow(df)){
  h <- match(df$team1[i], teams)
  a <- match(df$team2[i], teams)
  g[h, a] <- g[h, a] + 1
  g[a, h] <- g[a, h] + 1
}
for(i in 1:nrow(g)){
  g[i, i] <- sum(g[i, ])
}

grpf <- as.data.frame((diag(g) \* ratings) - goals_for)
row.names(grpf) <- teams

def_ratings <- solve(g, grpf[ ,1])
off_ratings <- ratings - def_ratings

**Comment by martineastwood** [comment]
It looks like R cannot solve the matrix, start off by checking that the variable df contains your data and contains the correct data types etc

**Comment by ghost** [comment]
try to change 
teams <- unique(c(df$team1, df$team2))
to
teams <- unique(c(levels(df$team1), levels(df$team2)))

**Comment by jonocarroll** [comment]
Alternatively, don't use factors:

```
df <- read.csv(f, stringsAsFactors = FALSE)
```

will correct the issues with `solve()`
