### ISSUE TITLE
http 403 code Return in Pythagorean

### ISSUE THREAD

**Issue by zawmoetun** [martineastwood/penalty#2]
Dear Sir,
This is Zaw again. When I use pythagorean program, I got error 403 when I read url. Can you help me? Error is below.

Response [http://www.statto.com/football/stats/england/premier-league/2015-2016/]
  Date: 2016-09-07 05:32
  Status: 403
  Content-Type: text/html
  Size: 279 B
<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>

**Comment by martineastwood** [comment]
Statto.com now checks your user agent string to check whether you are using a valid browser or not. For the time being you will need to use something like the rvest package to read the url and set the user agent string to something that matches a real browser, such as chrome or firefox

**Comment by zawmoetun** [comment]
Thank Sir.
